## Testing first scripts

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])
a.ndim

1

In [4]:
a.shape

(6,)

In [5]:
b = a.reshape((3,2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
print(b.ndim, b.shape)

2 (3, 2)


In [8]:
b[0][1] = 77
b

array([[ 1, 77],
       [ 3,  4],
       [ 5,  6]])

In [9]:
a

array([ 1, 77,  3,  4,  5,  6])

In [12]:
c = a.reshape((3,2)).copy()
c[0][0] = -99
c

array([[-99,  77],
       [  3,   4],
       [  5,   6]])

In [13]:
a

array([ 1, 77,  3,  4,  5,  6])

In [20]:
d = np.array([1,2,3,4,5])
d*2

array([ 2,  4,  6,  8, 10])

In [21]:
d**2

array([ 1,  4,  9, 16, 25])

In [23]:
a[np.array([1,3,4])]

array([77,  4,  5])

In [24]:
a > 4

array([False,  True, False, False,  True,  True])

In [25]:
a[a>4]

array([77,  5,  6])

In [26]:
a[a>4] = 4
a

array([1, 4, 3, 4, 4, 4])

In [27]:
a[2] = 100
a[0] = -100
a

array([-100,    4,  100,    4,    4,    4])

In [28]:
a.clip(0, 4)

array([0, 4, 4, 4, 4, 4])

In [29]:
c = np.array([1, 2, np.nan, 3, 4])

In [30]:
c

array([ 1.,  2., nan,  3.,  4.])

In [32]:
np.isnan(c)

array([False, False,  True, False, False])

In [33]:
c[~np.isnan(c)]

array([1., 2., 3., 4.])

In [36]:
np.mean(c[~np.isnan(c)])

2.5